name: Cache to Cachix

on:
  push:
    branches:
      - master

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v12
        with:
          name: balds
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Push to Cachix
        run: nix build --no-link --print-out-paths | cachix push balds
